
version: '3.1'
services:

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Pa55W00Rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=YaaniSearchDB
networks:
  default:
    external:
      name: searchengine_default